export type RDSEffectValue =
  'effect-new-effect-shadow' |
  'effect-new-effect-37571-blur-radius';

export type RDSBreakpointValue =
  'breakpoint-sm-up' |
  'breakpoint-md-up' |
  'breakpoint-lg-up' |
  'breakpoint-xlg-up';

export type RDSSpacingValue =
  'spacing-0' |
  'spacing-0-3' |
  'spacing-0-6' |
  'spacing-0-9' |
  'spacing-1' |
  'spacing-1-3' |
  'spacing-1-6' |
  'spacing-1-9' |
  'spacing-2' |
  'spacing-3' |
  'spacing-4' |
  'spacing-5' |
  'spacing-6' |
  'spacing-7' |
  'spacing-col-0' |
  'spacing-col-0-3' |
  'spacing-col-0-4' |
  'spacing-col-0-6' |
  'spacing-col-0-8' |
  'spacing-col-0-9' |
  'spacing-col-1' |
  'spacing-col-1-3' |
  'spacing-col-1-4' |
  'spacing-col-1-6' |
  'spacing-col-1-8' |
  'spacing-col-1-9' |
  'spacing-col-2' |
  'spacing-col-2-3' |
  'spacing-col-2-4' |
  'spacing-col-2-6' |
  'spacing-col-2-8' |
  'spacing-col-2-9' |
  'spacing-col-3' |
  'spacing-col-3-3' |
  'spacing-col-3-4' |
  'spacing-col-3-6' |
  'spacing-col-3-8' |
  'spacing-col-3-9' |
  'spacing-col-4' |
  'spacing-col-5' |
  'spacing-col-6' |
  'spacing-col-7' |
  'spacing-col-8' |
  'spacing-col-9' |
  'spacing-col-10' |
  'spacing-col-11' |
  'spacing-col-12' |
  'spacing-colvw-0' |
  'spacing-colvw-0-3' |
  'spacing-colvw-0-4' |
  'spacing-colvw-0-6' |
  'spacing-colvw-0-8' |
  'spacing-colvw-0-9' |
  'spacing-colvw-1' |
  'spacing-colvw-1-3' |
  'spacing-colvw-1-4' |
  'spacing-colvw-1-6' |
  'spacing-colvw-1-8' |
  'spacing-colvw-1-9' |
  'spacing-colvw-2' |
  'spacing-colvw-2-3' |
  'spacing-colvw-2-4' |
  'spacing-colvw-2-6' |
  'spacing-colvw-2-8' |
  'spacing-colvw-2-9' |
  'spacing-colvw-3' |
  'spacing-colvw-3-3' |
  'spacing-colvw-3-4' |
  'spacing-colvw-3-6' |
  'spacing-colvw-3-8' |
  'spacing-colvw-3-9' |
  'spacing-colvw-4' |
  'spacing-colvw-5' |
  'spacing-colvw-6' |
  'spacing-colvw-7' |
  'spacing-colvw-8' |
  'spacing-colvw-9' |
  'spacing-colvw-10' |
  'spacing-colvw-11' |
  'spacing-colvw-12';

export type RDSTypeValue =
  'type-text-10' |
  'type-text-10-size' |
  'type-text-10-weight' |
  'type-text-9' |
  'type-text-9-size' |
  'type-text-9-weight' |
  'type-text-8' |
  'type-text-8-size' |
  'type-text-8-weight' |
  'type-text-7' |
  'type-text-7-size' |
  'type-text-7-weight' |
  'type-text-6' |
  'type-text-6-size' |
  'type-text-6-weight' |
  'type-text-5' |
  'type-text-5-size' |
  'type-text-5-weight' |
  'type-text' |
  'type-text-size' |
  'type-text-weight' |
  'type-text-4' |
  'type-text-4-size' |
  'type-text-4-weight' |
  'type-text-3' |
  'type-text-3-size' |
  'type-text-3-weight' |
  'type-text-2' |
  'type-text-2-size' |
  'type-text-2-weight' |
  'type-text-1' |
  'type-text-1-size' |
  'type-text-1-weight' |
  'type-text-bold-10' |
  'type-text-bold-10-size' |
  'type-text-bold-10-weight' |
  'type-text-bold-9' |
  'type-text-bold-9-size' |
  'type-text-bold-9-weight' |
  'type-text-bold-8' |
  'type-text-bold-8-size' |
  'type-text-bold-8-weight' |
  'type-text-bold-7' |
  'type-text-bold-7-size' |
  'type-text-bold-7-weight' |
  'type-text-bold-6' |
  'type-text-bold-6-size' |
  'type-text-bold-6-weight' |
  'type-text-bold-5' |
  'type-text-bold-5-size' |
  'type-text-bold-5-weight' |
  'type-text-bold' |
  'type-text-bold-size' |
  'type-text-bold-weight' |
  'type-text-bold-4' |
  'type-text-bold-4-size' |
  'type-text-bold-4-weight' |
  'type-text-bold-3' |
  'type-text-bold-3-size' |
  'type-text-bold-3-weight' |
  'type-text-bold-2' |
  'type-text-bold-2-size' |
  'type-text-bold-2-weight' |
  'type-text-bold-1' |
  'type-text-bold-1-size' |
  'type-text-bold-1-weight';

export type RDSColorValue =
  'color-primary-1' |
  'color-primary-2' |
  'color-primary-3' |
  'color-primary-4' |
  'color-primary-5' |
  'color-primary' |
  'color-primary-6' |
  'color-primary-7' |
  'color-primary-8' |
  'color-primary-9' |
  'color-grey-0' |
  'color-grey-1' |
  'color-grey-2' |
  'color-grey-3' |
  'color-grey-4' |
  'color-grey-5' |
  'color-grey' |
  'color-grey-6' |
  'color-grey-7' |
  'color-grey-8' |
  'color-grey-9' |
  'color-grey-95' |
  'color-grey-10' |
  'color-secondary-1' |
  'color-secondary-2' |
  'color-secondary-3' |
  'color-secondary-4' |
  'color-secondary-5' |
  'color-secondary' |
  'color-secondary-6' |
  'color-secondary-7' |
  'color-secondary-8' |
  'color-secondary-9';

export type RDSValue =
  RDSEffectValue |
  RDSBreakpointValue |
  RDSSpacingValue |
  RDSTypeValue |
  RDSColorValue;
